### ISSUE TITLE
Resource URL localized

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-multilang#11]
The resources URLs are not localized (both for the IT and DE the same URL is used). We would like instead to be able to localize them, in order to avoid duplication of resources in the same dataset.

A reference dataset containing the same PDF resource for each supported language can be found at the URL below:

http://dati.retecivica.bz.it/it/dataset/catalogo-beni-culturali

Note: 
A solution could be the management of a simple localized URL for external resources but, for internal resources, we should to expect to upload documents in multiple languages and list only the resources corresponding to the Ckan's locale set.

This work should be implemented as ckanext-multilang enhancement

**Comment by cezio** [comment]
Should this be global, or admin should be able to designate if specific dataset should use localized resource urls?

**Comment by tdipisa** [comment]
Interesting @cezio, which is your proposal about that point? It would be nice the possibility to have this functionality disabled by default (a config properti in .ini file could be used to enable this).

**Comment by cezio** [comment]
Rought idea:
 * config variable: `localized_resources` to enable the feature with `true` value
 * resource will have extra `lang` field
 * edit will show all resources
 * view will show resources without/with empty `lang` or with `lang` equal to current language
 
For implementation, due to IDatasetForm plugin limitations, we should add some integration code to ckanext-dcatapit, so it will include multilang's resource schema. Otherwise, Multilang should have IDatasetForm implementation which will modify resource schema standalone.

Multilang/Dcatapit should use IDatasetForm.read_template() to return customized read template which will filter out resources that has different `lang` value. 

Edit template should probably be customized as well to visually distinct per-language resources.

**Comment by tdipisa** [comment]
@etj can you provide your opinion on this?

**Comment by cezio** [comment]
One question here: should dataset owner (or anyone who can modify resources), see all resources? I don't see any other way they would access resources.

**Comment by cezio** [comment]
Implementation notes:
 * to enable this feature, set `ckanext.multilang.localized_resources` to `true`.
 * there's multilang's `IDatasetForm` plugin implementation which is available as `multilang_resources` plugin. However, if `dcatapit_pkg` is used, and localized resources flag is enabled, dcatapit's plugin will reuse multilang's plugin internally. No need to use `multilang_resources` in that case.
 * There's new `lang` field in resource. It should contain 2-letter code of language.
 * If current user has permissions to edit resources, he'll see all resources. If it's regular user, he'll see only resources that either don't have language set, or have language set to current language.

**Comment by tdipisa** [comment]
@cezio please can you update your ml-integration (ckanext-dcatapit) branch with the latest updates provided on official master?

**Comment by cezio** [comment]
@tdipisa updated

**Comment by tdipisa** [comment]
@cezio, I installed locally your branches of dcatapit (ml-integration) and multilang (11_localized_resource_urls) but I got the following error while clicking the button (in dataset create form) to create the resource:

...

File '/usr/lib/ckan/default/src/ckanext-multilang/ckanext/multilang/templates/package/snippets/resource_additional_fields.html', line 39 in top-level template code
  {% call input_block('lang', field.label, errors[field.name]) %}
File '/usr/lib/ckan/default/src/ckanext-multilang/ckanext/multilang/templates/package/snippets/resource_additional_fields.html', line 24 in template
  {{ caller() }}
File '/usr/lib/ckan/default/src/ckanext-multilang/ckanext/multilang/templates/package/snippets/resource_additional_fields.html', line 42 in template
  <option value="{{ locale }}" {% if locale.identifier == data.get(field.name) %}selected="selected"{% endif %}>
UndefinedError: 'str object' has no attribute 'get'

I need to see this running to complete the evaluation of this implementation.

**Comment by cezio** [comment]
Thx for report. should be fixed with https://github.com/cezio/ckanext-multilang/commit/4e4168dd3ff652655bec7050b4760cf3f62e4382
