### ISSUE TITLE
Error 500 with CKAN 2.10

### ISSUE THREAD

**Issue by filos1983** [geosolutions-it/ckanext-multilang#42]
Hello, I'm trying to install this plugin on my CKAN 2.10 instance but after the installation the webserver (Nginx) returns Error 500 without other messages. Is ckanext-multilang compatible with this version of CKAN? Is there a way to check what's going wrong?

Thanks

**Comment by tdipisa** [comment]
Hi you should maybe check also the CKAN log file to see what's going wrong in your installation. As for the compatibility, you need at least CKAN 2.4; in the [readme file](https://github.com/geosolutions-it/ckanext-multilang#requirements) further info on involved requirements. The last update we did is 2 years hold for compatibility with 2.9. Therefore, compatibility with last Ckan 2.10 is not guaranteed. I hope this can help.
